/**
 * analytics.ts — Marketing analytics: UTM capture, feature events, DAU/MAU crons.
 *
 * Tables: utm_events, user_activity, feature_events
 * Crons: daily DAU aggregation, anomaly/spike detection
 */
import { query, mutation, action, internalMutation } from "./_generated/server";
import { v } from "convex/values";
import { getAuthUserId } from "@convex-dev/auth/server";
import { cronJobs } from "convex/server";
import { internal } from "./_generated/api";

// ─── HELPERS ────────────────────────────────────────────────────────────────

function getDateStr(offsetDays = 0): string {
    const d = new Date();
    d.setUTCDate(d.getUTCDate() + offsetDays);
    return d.toISOString().slice(0, 10); // "YYYY-MM-DD"
}

function getSessionId(): string {
    // Client-side session ID — generated by AnalyticsProvider and stored in localStorage.
    // Stays stable for the browser tab session.
    return Math.random().toString(36).slice(2);
}

// ─── VISITOR ID ────────────────────────────────────────────────────────────

/** Stable anonymous visitor ID stored in localStorage under `sg_visitor_id`. */
function getVisitorId(): string {
    // On the client, this is read from localStorage by the AnalyticsProvider.
    // Server-side, we accept a visitorId arg — no access to localStorage.
    return "";
}

// ─── UTM MUTATIONS ─────────────────────────────────────────────────────────

/** Record first-touch UTM data when a visitor lands on the site. */
export const recordUtmEvent = mutation({
    args: {
        visitorId: v.string(),
        utmSource: v.optional(v.string()),
        utmMedium: v.optional(v.string()),
        utmCampaign: v.optional(v.string()),
        utmTerm: v.optional(v.string()),
        utmContent: v.optional(v.string()),
        referringDomain: v.optional(v.string()),
        landingPage: v.string(),
    },
    handler: async (ctx, args) => {
        // Only record if at least one UTM param is present
        if (!args.utmSource && !args.utmMedium && !args.utmCampaign) {
            return null;
        }

        const id = await ctx.db.insert("utm_events", {
            visitorId: args.visitorId,
            utmSource: args.utmSource ?? undefined,
            utmMedium: args.utmMedium ?? undefined,
            utmCampaign: args.utmCampaign ?? undefined,
            utmTerm: args.utmTerm ?? undefined,
            utmContent: args.utmContent ?? undefined,
            referringDomain: args.referringDomain ?? undefined,
            landingPage: args.landingPage,
            userId: undefined,
            createdAt: Date.now(),
        });

        return id;
    },
});

/** Backfill userId on an existing UTM event after signup.
 * If userId is not provided, resolves it from the current auth context.
 */
export const linkUtmToUser = mutation({
    args: {
        visitorId: v.string(),
        utmEventId: v.optional(v.id("utm_events")),
    },
    handler: async (ctx, args) => {
        // Resolve userId from auth context if not provided
        let userId = await getAuthUserId(ctx);
        if (!userId) return;

        if (args.utmEventId) {
            await ctx.db.patch(args.utmEventId, { userId });
            return;
        }
        // Fallback: find the most recent UTM event for this visitor and link it
        const event = await ctx.db
            .query("utm_events")
            .withIndex("by_visitor_id", (q) => q.eq("visitorId", args.visitorId))
            .first();
        if (event) {
            await ctx.db.patch(event._id, { userId });
        }
    },
});

// ─── FEATURE EVENTS ────────────────────────────────────────────────────────

/**
 * Record a named feature event.
 * Call this from any mutation or client-side hook for key conversion actions.
 *
 * eventName examples:
 *   signup_completed, onboarding_finished, oracle_first, oracle_message,
 *   journal_entry, upgrade_to_popular, upgrade_to_premium, referral_completed,
 *   dashboard_viewed, daily_horoscope_viewed, cosmic_weather_viewed
 */
export const recordFeatureEvent = mutation({
    args: {
        eventName: v.string(),
        userId: v.optional(v.id("users")),
        sessionId: v.string(),
        metadata: v.optional(v.record(v.string(), v.string())),
        utmEventId: v.optional(v.id("utm_events")),
        funnelStage: v.optional(v.union(
            v.literal("signup"),
            v.literal("activation"),
            v.literal("engagement"),
            v.literal("revenue"),
        )),
    },
    handler: async (ctx, args) => {
        const now = Date.now();
        const today = new Date(now).toISOString().slice(0, 10);

        const id = await ctx.db.insert("feature_events", {
            eventName: args.eventName,
            userId: args.userId ?? undefined,
            eventDate: today,
            timestamp: now,
            sessionId: args.sessionId,
            metadata: args.metadata ?? undefined,
            utmEventId: args.utmEventId ?? undefined,
            funnelStage: args.funnelStage ?? undefined,
        });

        return id;
    },
});

/**
 * Backfill userId onto feature events that were recorded anonymously.
 * Called after signup to attribute pre-auth events.
 */
export const backfillUserIdOnEvents = mutation({
    args: { userId: v.id("users"), sessionId: v.string() },
    handler: async (ctx, args) => {
        const anonymousEvents = await ctx.db
            .query("feature_events")
            .withIndex("by_user_event", (q) =>
                q.eq("userId", undefined).eq("eventName", "session_start")
            )
            .filter((q) => q.eq(q.field("sessionId"), args.sessionId))
            .collect();

        for (const evt of anonymousEvents) {
            await ctx.db.patch(evt._id, { userId: args.userId });
        }
    },
});

// ─── ANALYTICS QUERIES ─────────────────────────────────────────────────────

/** Daily signups grouped by channel (UTM source). */
export const dailySignupsByChannel = query({
    args: { startDate: v.string(), endDate: v.string() },
    handler: async (ctx, args) => {
        const events = await ctx.db
            .query("feature_events")
            .withIndex("by_date", (q) =>
                q.gte("eventDate", args.startDate).lte("eventDate", args.endDate)
            )
            .collect();

        // Filter to signup events client-side (compound index not available for date-only)
        const signupEvents = events.filter((e) => e.eventName === "signup_completed");

        // Group signups by UTM source
        const byChannel: Record<string, number> = {};
        for (const evt of signupEvents) {
            if (evt.utmEventId) {
                const utm = await ctx.db.get(evt.utmEventId);
                const src = utm?.utmSource ?? "direct";
                byChannel[src] = (byChannel[src] ?? 0) + 1;
            } else {
                byChannel["direct"] = (byChannel["direct"] ?? 0) + 1;
            }
        }

        // Group signups by date
        const byDate: Record<string, number> = {};
        for (const evt of signupEvents) {
            byDate[evt.eventDate] = (byDate[evt.eventDate] ?? 0) + 1;
        }

        return {
            total: signupEvents.length,
            byChannel,
            byDate,
        };
    },
});

/** Weekly active users count (distinct users with any activity in a date range). */
export const weeklyActiveUsers = query({
    args: { startDate: v.string(), endDate: v.string() },
    handler: async (ctx, args) => {
        const rows = await ctx.db
            .query("user_activity")
            .withIndex("by_date", (q) =>
                q.gte("date", args.startDate).lte("date", args.endDate)
            )
            .collect();

        const uniqueUsers = new Set(rows.map((r) => r.userId.toString()));
        return {
            wau: uniqueUsers.size,
            totalSessions: rows.reduce((s, r) => s + r.sessionsCount, 0),
            totalDurationMs: rows.reduce((s, r) => s + r.totalSessionDurationMs, 0),
        };
    },
});

/** Top traffic sources by UTM campaign (signups attributed). */
export const topTrafficSources = query({
    args: { limit: v.optional(v.number()) },
    handler: async (ctx, args) => {
        const limit = args.limit ?? 10;
        const events = await ctx.db
            .query("feature_events")
            .withIndex("by_event_date", (q) =>
                q.eq("eventName", "signup_completed")
            )
            .collect();

        const campaignCounts: Record<string, number> = {};
        for (const evt of events) {
            if (evt.utmEventId) {
                const utm = await ctx.db.get(evt.utmEventId);
                if (utm?.utmCampaign) {
                    campaignCounts[utm.utmCampaign] =
                        (campaignCounts[utm.utmCampaign] ?? 0) + 1;
                }
            }
        }

        return Object.entries(campaignCounts)
            .sort(([, a], [, b]) => b - a)
            .slice(0, limit)
            .map(([campaign, count]) => ({ campaign, count }));
    },
});

/** Referral program summary: pending, completed, total stardust. */
export const referralProgramSummary = query({
    args: {},
    handler: async (ctx) => {
        const allReferrals = await ctx.db.query("referrals").collect();
        const completed = allReferrals.filter((r) => r.status === "completed");
        const pending = allReferrals.filter((r) => r.status === "pending");
        return {
            total: allReferrals.length,
            completed: completed.length,
            pending: pending.length,
            totalStardustAwarded: completed.reduce((s, r) => s + r.rewardAmount, 0),
        };
    },
});

/** Full dashboard snapshot for a date range — used by weekly report. */
export const dashboardSnapshot = query({
    args: {
        startDate: v.string(),
        endDate: v.string(),
    },
    handler: async (ctx, args) => {
        // Signups by channel
        const signupEvents = await ctx.db
            .query("feature_events")
            .withIndex("by_event_date", (q) =>
                q
                    .eq("eventName", "signup_completed")
                    .gte("eventDate", args.startDate)
                    .lte("eventDate", args.endDate)
            )
            .collect();

        const byChannel: Record<string, number> = { direct: 0 };
        const byDate: Record<string, number> = {};
        for (const evt of signupEvents) {
            const date = evt.eventDate;
            byDate[date] = (byDate[date] ?? 0) + 1;
            if (evt.utmEventId) {
                const utm = await ctx.db.get(evt.utmEventId);
                const src = utm?.utmSource ?? "direct";
                byChannel[src] = (byChannel[src] ?? 0) + 1;
            } else {
                byChannel["direct"]++;
            }
        }

        // WAU
        const activityRows = await ctx.db
            .query("user_activity")
            .withIndex("by_date", (q) =>
                q.gte("date", args.startDate).lte("date", args.endDate)
            )
            .collect();
        const uniqueUsers = new Set(activityRows.map((r) => r.userId.toString()));

        // Top features used — use by_date index (date-only, no eventName filter)
        const featureEvents = await ctx.db
            .query("feature_events")
            .withIndex("by_date", (q) =>
                q.gte("eventDate", args.startDate).lte("eventDate", args.endDate)
            )
            .collect();
        const featureCounts: Record<string, number> = {};
        for (const evt of featureEvents) {
            featureCounts[evt.eventName] = (featureCounts[evt.eventName] ?? 0) + 1;
        }
        const topFeatures = Object.entries(featureCounts)
            .sort(([, a], [, b]) => b - a)
            .slice(0, 10)
            .map(([name, count]) => ({ name, count }));

        // Referrals
        const allReferrals = await ctx.db.query("referrals").collect();
        const completed = allReferrals.filter((r) => r.status === "completed").length;
        const pending = allReferrals.filter((r) => r.status === "pending").length;

        // Subscription tiers
        const allUsers = await ctx.db.query("users").collect();
        const byTier = { free: 0, popular: 0, premium: 0 };
        for (const u of allUsers) {
            byTier[u.tier] = (byTier[u.tier] ?? 0) + 1;
        }

        return {
            signups: { total: signupEvents.length, byChannel, byDate },
            wau: uniqueUsers.size,
            topFeatures,
            referrals: { total: allReferrals.length, completed, pending },
            byTier,
        };
    },
});

// ─── SESSION START (anonymous — called from client on first page load) ──────

export const recordSessionStart = mutation({
    args: {
        visitorId: v.string(),
        sessionId: v.string(),
        utmEventId: v.optional(v.id("utm_events")),
    },
    handler: async (ctx, args) => {
        const now = Date.now();
        const today = new Date(now).toISOString().slice(0, 10);
        await ctx.db.insert("feature_events", {
            eventName: "session_start",
            userId: undefined,
            eventDate: today,
            timestamp: now,
            sessionId: args.sessionId,
            metadata: { visitorId: args.visitorId },
            utmEventId: args.utmEventId ?? undefined,
            funnelStage: undefined,
        });
    },
});

// Note: Cron jobs are registered in crons.ts:
//   - aggregate-daily-activity (03:00 UTC)
//   - detect-analytics-anomalies (04:00 UTC)

// ─── SHARE TRACKING ─────────────────────────────────────────────────────────

export const trackShare = mutation({
  args: {
    shareType: v.string(),
    platform: v.string(),
    utmSource: v.optional(v.string()),
  },
  handler: async (ctx, args) => {
    const userId = await getAuthUserId(ctx);
    await ctx.db.insert("share_events", {
      userId: userId ?? null,
      shareType: args.shareType,
      platform: args.platform,
      utmSource: args.utmSource ?? null,
      createdAt: Date.now(),
    });
  },
});
