import { ElementType } from "./elements";

export interface SignData {
    id: string;
    name: string;
    archetypeName: string;
    coreStrategy: string;
    cognitiveInsight: string;
    elementalTruth: string;
    strengths: string[];
    weaknesses: string[];
    compositionalAdverbialPhrase: string; // The "How"
    element: ElementType;

    // Legacy Data
    dates: string;
    traits: string;
    modality: "Cardinal" | "Fixed" | "Mutable";
    ruler: string;
    polarity: "Masculine" | "Feminine";
    stone: string;
    essenceFull: string;
    motto: string;
    coreDesire: string;
    goal: string;
    greatestFear: string;
}

export const compositionalSigns: SignData[] = [
    {
        id: "aries",
        name: "Aries",
        element: "Fire",
        archetypeName: "The Trailblazer",
        coreStrategy: "Rapid decision-making, taking the first step before others are ready, and embracing conflict as a catalyst for change.",
        cognitiveInsight: "Psychologically driven by dopamine rewards tied to novelty and overcoming resistance, exhibiting a high bias for action and a low tolerance for inefficiency.",
        elementalTruth: "You are the spark that starts the blaze. Your fire is raw, unfiltered initiation. You don't sustain—you activate.",
        strengths: ["Activation and mobilization of energy", "Overcoming systemic inertia", "Decisive forward momentum"],
        weaknesses: ["Impulsivity", "Start-up energy burnout", "Lack of sustained follow-through"],
        compositionalAdverbialPhrase: "with aggressive autonomy and decisive speed",
        dates: "Mar 21 - Apr 19",
        traits: "Energetic, adventurous, and enthusiastic.",
        modality: "Cardinal",
        ruler: "mars",
        polarity: "Masculine",
        stone: "Diamond",
        essenceFull: "The pioneer of the zodiac, Aries is a force of nature. As the first sign, they possess an inherent need to lead, to initiate, and to conquer. Their energy is raw, unfiltered, and deeply connected to the spark of existence itself.",
        motto: "I am, therefore I do.",
        coreDesire: "Autonomy and forward momentum.",
        goal: "To initiate action and prove existence through impact.",
        greatestFear: "Stagnation, being controlled, or fading into the background.",
    },
    {
        id: "taurus",
        name: "Taurus",
        element: "Earth",
        archetypeName: "The Builder",
        coreStrategy: "Methodical progress, risk aversion, and utilizing the five senses to verify reality.",
        cognitiveInsight: "You value empirical evidence over theory. If you can’t touch it, see it, or quantify it, you are skeptical. Your \"stubbornness\" is actually high cognitive persistence—once you verify a fact or method is sound, you stick to it to maximize efficiency.",
        elementalTruth: "You are the bedrock. Your earth doesn't shift—it anchors. You build structures meant to last, accumulating value through patience and consistency.",
        strengths: ["Sustainment and endurance", "Methodical execution", "Sensory awareness and appreciation"],
        weaknesses: ["Inertia and resistance to change", "Over-attachment to comfort", "Slowness to adapt to novelty"],
        compositionalAdverbialPhrase: "through methodical stabilization and risk-averse endurance",
        dates: "Apr 20 - May 20",
        traits: "Patient, reliable, and warmhearted.",
        modality: "Fixed",
        ruler: "venus",
        polarity: "Feminine",
        stone: "Emerald",
        essenceFull: "Taurus represents the physical world in its most beautiful and stable form. They are the builders and the keepers of comfort, find joy in the senses, and possess an unwavering loyalty that grounds everyone around them.",
        motto: "Quality over quantity, always.",
        coreDesire: "Stability and sensory satisfaction.",
        goal: "To build sustainable systems and accumulate resources (emotional or material) that last.",
        greatestFear: "Scarcity, sudden instability, or being rushed into poor quality.",
    },
    {
        id: "gemini",
        name: "Gemini",
        element: "Air",
        archetypeName: "The Connector",
        coreStrategy: "Adaptability, humor, and collecting data points from diverse sources.",
        cognitiveInsight: "You possess high \"Cognitive Flexibility.\" Your brain craves new neural pathways, which manifests as a need for variety. You aren't \"two-faced\"; you are context-dependent, rapidly adjusting your behavior to optimize social friction.",
        elementalTruth: "You are the wind. Your air doesn't concentrate—it circulates. You gather information from one place and carry it to another, naturally connecting disparate ideas and people.",
        strengths: ["Translation of complex ideas", "Rapid context switching", "Social adaptability"],
        weaknesses: ["Analysis paralysis", "Scattered focus", "Lack of sustained depth"],
        compositionalAdverbialPhrase: "with rapid adaptability and continuous data collection",
        dates: "May 21 - Jun 20",
        traits: "Adaptable, versatile, and intellectual.",
        modality: "Mutable",
        ruler: "mercury",
        polarity: "Masculine",
        stone: "Agate",
        essenceFull: "Gemini is the breath of curiosity that connects ideas. Always seeking, always learning, they embody the dual nature of the mind. They are the messengers of the zodiac, weaving together disparate threads of information into a cohesive whole.",
        motto: "Everything is interesting if you look close enough.",
        coreDesire: "Intellectual variety and social connection.",
        goal: "To gather information and bridge gaps between different people and ideas.",
        greatestFear: "Boredom, mental confinement, or being \"out of the loop.\"",
    },
    {
        id: "cancer",
        name: "Cancer",
        element: "Water",
        archetypeName: "The Protector",
        coreStrategy: "Establishing deep roots, reading emotional undercurrents, and defensive withdrawal when threatened.",
        cognitiveInsight: "You are hyper-attentive to non-verbal cues and micro-expressions. Your \"moodiness\" is a reaction to environmental stimuli that others miss. You value tribal cohesion and security.",
        elementalTruth: "You are the wave. Your water doesn't just feel—it moves. You respond to emotional currents and create environments where others feel safe enough to be vulnerable.",
        strengths: ["High emotional intelligence", "Creation of psychological safety", "Visceral understanding of unstated needs"],
        weaknesses: ["Over-identification with others' emotions", "Defensive withdrawal under stress", "Difficulty letting go"],
        compositionalAdverbialPhrase: "through intuitive care and emotional self-protection",
        dates: "Jun 21 - Jul 22",
        traits: "Emotional, loving, and intuitive.",
        modality: "Cardinal",
        ruler: "moon",
        polarity: "Feminine",
        stone: "Pearl",
        essenceFull: "Cancer is the emotional foundation of the zodiac. Deeply intuitive and fiercely protective, they navigate life through the tides of feeling. To a Cancer, home is not a place, but a state of emotional safety and belonging.",
        motto: "To care is to be strong.",
        coreDesire: "Emotional safety and belonging.",
        goal: "To create a sanctuary (home/community) where defenses can be lowered.",
        greatestFear: "Vulnerability without reciprocity; being left exposed.",
    },
    {
        id: "leo",
        name: "Leo",
        element: "Fire",
        archetypeName: "The Protagonist",
        coreStrategy: "Radiating confidence (even when faked), generosity, and assuming the lead role in one's own life.",
        cognitiveInsight: "You have a high drive for \"Social Dominance\" in the benevolent sense—you want to lead and inspire. You understand the psychology of presentation: perception is reality.",
        elementalTruth: "You are the eternal flame. Your fire doesn't ignite—it radiates. You turn raw energy into a steady source that others rely upon.",
        strengths: ["Magnetic social presence", "Creative self-expression", "Inspiring morale in groups"],
        weaknesses: ["Reliance on external validation", "Fear of mediocrity", "Resistance to sharing the spotlight"],
        compositionalAdverbialPhrase: "with radiant self-assurance and dramatic visibility",
        dates: "Jul 23 - Aug 22",
        traits: "Generous, warmhearted, and creative.",
        modality: "Fixed",
        ruler: "sun",
        polarity: "Masculine",
        stone: "Ruby",
        essenceFull: "Leo is the heart of the zodiac, radiating warmth, creativity, and authority. They are natural leaders who lead with love and a dramatic flair. Their presence is a reminder of the power of individual expression and the courage to be seen.",
        motto: "Shine, so others have permission to do the same.",
        coreDesire: "Self-expression and validation.",
        goal: "To leave a unique, visible mark on the world (legacy).",
        greatestFear: "Being ignored, mediocrity, or public humiliation.",
    },
    {
        id: "virgo",
        name: "Virgo",
        element: "Earth",
        archetypeName: "The Optimizer",
        coreStrategy: "Critical analysis, discernment, and focusing on the details others overlook.",
        cognitiveInsight: "You are a systems thinker. You don't \"nag\"; you troubleshoot. Your brain is wired for pattern recognition regarding efficiency. If something is broken, your cognitive itch demands you fix it.",
        elementalTruth: "You are the cultivated garden. Your earth doesn't just exist—it optimizes. You turn raw material into something functional and efficient.",
        strengths: ["Instant flaw recognition", "Methodical refinement", "Dedication to functional perfection"],
        weaknesses: ["Analysis paralysis", "Imposter syndrome", "Harsh self-criticism"],
        compositionalAdverbialPhrase: "through systematic analysis and relentless refinement",
        dates: "Aug 23 - Sep 22",
        traits: "Modest, shy, and meticulous.",
        modality: "Mutable",
        ruler: "mercury",
        polarity: "Feminine",
        stone: "Sapphire",
        essenceFull: "Virgo seeks perfection through service and analysis. Meticulous and thoughtful, they find the hidden patterns in chaos. They represent the Earth in its most refined state, where every detail serves a higher purpose of healing and organization.",
        motto: "There is a better way to do this.",
        coreDesire: "Competence, order, and utility.",
        goal: "To refine systems, heal chaos, and achieve functional perfection.",
        greatestFear: "Uselessness, chaos, or being criticized for errors.",
    },
    {
        id: "libra",
        name: "Libra",
        element: "Air",
        archetypeName: "The Harmonizer",
        coreStrategy: "Negotiation, charm, and seeing the validity in opposing viewpoints.",
        cognitiveInsight: "You possess high \"Social Intelligence.\" You are a dialectical thinker—you naturally see the thesis and antithesis of every argument. You prioritize group cohesion over individual ego.",
        elementalTruth: "You are the atmosphere. Your air doesn't scatter—it balances. You instinctively sense when things are off-kilter and work to restore harmony.",
        strengths: ["Calibration of social dynamics", "Objective fairness", "Mastery of diplomacy"],
        weaknesses: ["Indecision from over-weighing options", "Suppression of authentic anger", "Conflict avoidance"],
        compositionalAdverbialPhrase: "by calibrating relational mechanics and seeking equilibrium",
        dates: "Sep 23 - Oct 22",
        traits: "Diplomatic, urbane, and romantic.",
        modality: "Cardinal",
        ruler: "venus",
        polarity: "Masculine",
        stone: "Opal",
        essenceFull: "Libra is the pursuit of harmony through relationship. They are the architects of balance, seeking beauty and justice in all things. Through the mirror of the 'other', Libra learns the grace of compromise and the art of peace.",
        motto: "Balance is not a destination, it's a practice.",
        coreDesire: "Harmony, beauty, and objective fairness.",
        goal: "To align their environment and relationships into a state of equilibrium.",
        greatestFear: "Conflict, isolation, or making the \"wrong\" permanent decision.",
    },
    {
        id: "scorpio",
        name: "Scorpio",
        element: "Water",
        archetypeName: "The Alchemist",
        coreStrategy: "Strategic silence, deep observation, and testing the loyalty of others.",
        cognitiveInsight: "You have an \"Investigative\" personality type. You are not satisfied with surface-level data; you look for root causes and hidden motives, refusing to engage in cognitive dissonance.",
        elementalTruth: "You are the abyss. Your water doesn't flow—it transforms. You dive beneath literal surface explanations to understand the true nature of things.",
        strengths: ["Psychological resilience", "Unflinching focus", "Mastery over crisis and transformation"],
        weaknesses: ["Tendency towards paranoia", "Vindictiveness when betrayed", "Holding onto psychological debts"],
        compositionalAdverbialPhrase: "with piercing intensity and transformative depths",
        dates: "Oct 23 - Nov 21",
        traits: "Determined, forceful, and emotional.",
        modality: "Fixed",
        ruler: "pluto",
        polarity: "Feminine",
        stone: "Topaz",
        essenceFull: "Scorpio is the sign of transformation, depth, and intensity. They are the detectives of the soul, unafraid of the shadows and the mysteries of life. Their power lies in their ability to endure, to regenerate, and to speak the unspoken truth.",
        motto: "I survive, I transform, I rise.",
        coreDesire: "Intensity and uncovering the truth beneath the surface.",
        goal: "To master the self and understand the taboo/hidden mechanics of life.",
        greatestFear: "Betrayal and powerlessness.",
    },
    {
        id: "sagittarius",
        name: "Sagittarius",
        element: "Fire",
        archetypeName: "The Explorer",
        coreStrategy: "Humor, risk-taking, and constantly zooming out to see the \"Big Picture.\"",
        cognitiveInsight: "You score high in \"Openness to Experience.\" You have a biological drive for novelty. You are an information-forager who learns best through immersion and trial-and-error.",
        elementalTruth: "You are the spreading flame. Your fire doesn't stay put—it explores. You carry energy across boundaries and into unfamiliar territory.",
        strengths: ["Visionary perspective", "High adaptability to the unknown", "Philosophical optimism"],
        weaknesses: ["Tactless bluntness", "Fear of confinement or commitment", "Overlooking immediate details"],
        compositionalAdverbialPhrase: "with boundless exploration and philosophical expansion",
        dates: "Nov 22 - Dec 21",
        traits: "Optimistic, freedom-loving, and honest.",
        modality: "Mutable",
        ruler: "jupiter",
        polarity: "Masculine",
        stone: "Turquoise",
        essenceFull: "Sagittarius is the eternal seeker of truth and wisdom. With their eyes on the horizon, they embody the spirit of adventure and the joy of philosophy. They are the fire that lights the way to higher understanding and boundless freedom.",
        motto: "Don't fence me in.",
        coreDesire: "Expansion (mental or physical) and freedom.",
        goal: "To find meaning and truth through experience.",
        greatestFear: "Confinement, boredom, and having to follow arbitrary rules.",
    },
    {
        id: "capricorn",
        name: "Capricorn",
        element: "Earth",
        archetypeName: "The Strategist",
        coreStrategy: "Delayed gratification, pragmatic planning, and emotional regulation.",
        cognitiveInsight: "You are \"Goal-Oriented\" and \"Conscientious.\" You view life as a resource management game, preferring to invest emotional energy where it yields a tangible return.",
        elementalTruth: "You are the mountain. Your earth doesn't settle—it ascends. You measure life in milestones, not moments, building toward something greater with each step.",
        strengths: ["Execution of long-term goals", "Unwavering discipline", "Mastery of structural integrity"],
        weaknesses: ["Ruthlessness with self limits", "Equating worth with productivity", "Emotional rigidity"],
        compositionalAdverbialPhrase: "through disciplined ambition and structural mastery",
        dates: "Dec 22 - Jan 19",
        traits: "Practical, prudent, and ambitious.",
        modality: "Cardinal",
        ruler: "saturn",
        polarity: "Feminine",
        stone: "Garnet",
        essenceFull: "Capricorn is the climber of the zodiac, representing discipline, ambition, and the wisdom of time. They understand that true greatness is built stone by stone. They are the masters of the material realm, turning vision into lasting legacy.",
        motto: "Discipline is freedom.",
        coreDesire: "Achievement and autonomy through mastery.",
        goal: "To build a legacy of tangible value and structural integrity.",
        greatestFear: "Failure, public embarrassment, and dependency on others.",
    },
    {
        id: "aquarius",
        name: "Aquarius",
        element: "Air",
        archetypeName: "The Innovator",
        coreStrategy: "Detachment (viewing life objectively), radical honesty, and networking.",
        cognitiveInsight: "You are a non-conformist by nature. You have a low need for social approval and a high need for intellectual autonomy, able to analyze systems without bias.",
        elementalTruth: "You are the frequency. Your air doesn't adapt—it broadcasts. You transmit ideas that challenge the status quo, often ahead of when others are ready to receive them.",
        strengths: ["Divergent thinking", "Objective systems analysis", "Forward-thinking innovation"],
        weaknesses: ["Intellectual arrogance (God-complex)", "Disconnect from one-on-one intimacy", "Rebelliousness for its own sake"],
        compositionalAdverbialPhrase: "using detached objectivity and disruptive insight",
        dates: "Jan 20 - Feb 18",
        traits: "Friendly, humanitarian, and honest.",
        modality: "Fixed",
        ruler: "uranus",
        polarity: "Masculine",
        stone: "Amethyst",
        essenceFull: "Aquarius is the visionary of the zodiac, focused on the future and the collective good. They are the rebels with a cause, challenging traditions to make way for innovation and humanitarian ideals. They dance to the beat of an cosmic drum.",
        motto: "Break the rules to build a better game.",
        coreDesire: "Freedom of thought and progress for the collective.",
        goal: "To disrupt outdated systems and implement future-proof solutions.",
        greatestFear: "Conformity, losing individuality, and emotional suffocation.",
    },
    {
        id: "pisces",
        name: "Pisces",
        element: "Water",
        archetypeName: "The Dreamer",
        coreStrategy: "Intuition, creativity, and adaptability (flowing like water).",
        cognitiveInsight: "You possess \"High Sensory Processing Sensitivity.\" Your brain absorbs more environmental data than the average person, processing through pattern recognition and feeling rather than linear logic.",
        elementalTruth: "You are the ocean. Your water doesn't contain—it merges. You experience life through fluid boundaries, absorbing the emotions and energies around you.",
        strengths: ["Holistic synthesis", "Limitless empathy", "Adaptable intuitive logic"],
        weaknesses: ["Escapism", "Lack of energetic boundaries", "Vulnerability to being consumed by others"],
        compositionalAdverbialPhrase: "with empathetic dissolution of boundaries and intuitive synthesis",
        dates: "Feb 19 - Mar 20",
        traits: "Imaginative, sensitive, and compassionate.",
        modality: "Mutable",
        ruler: "neptune",
        polarity: "Feminine",
        stone: "Aquamarine",
        essenceFull: "Pisces is the ocean of the zodiac, where all boundaries dissolve into spiritual oneness. Deeply empathetic and highly imaginative, they exist between worlds. They are the dreamers who remind us that we are all part of a larger, mystical whole.",
        motto: "Reality is just one layer of existence.",
        coreDesire: "Transcendent connection and unity.",
        goal: "To dissolve boundaries and alleviate suffering through understanding.",
        greatestFear: "Being consumed by the harshness of reality or total isolation.",
    }
];
